//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Textila.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Count
    {
        public int CountId { get; set; }
        public Nullable<int> CountName { get; set; }
        public Nullable<int> SingleDouble { get; set; }
        public Nullable<int> Blend { get; set; }
        public string Description { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual Blend Blend1 { get; set; }
    }
}
